# Generated by Django 2.2.1 on 2019-05-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('business_id', models.IntegerField(verbose_name='业务模块id')),
                ('business_name', models.CharField(blank=True, default='', max_length=50, verbose_name='业务模块')),
                ('load', models.IntegerField(verbose_name='机器负载')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
